// <auto-generated />
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328120000_AddGoogleAuthFields")]
    partial class AddGoogleAuthFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelLayer.Models.User", b =>
            {
                b.Property<int>("UserId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));
                b.Property<string>("AuthProvider").IsRequired().HasDefaultValue("local").HasColumnType("nvarchar(max)");
                b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("FirstName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("GoogleId").HasColumnType("nvarchar(max)");
                b.Property<string>("HashedPassword").HasColumnType("nvarchar(max)");
                b.Property<string>("LastName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("ProfilePicture").HasColumnType("nvarchar(max)");
                b.Property<string>("Salt").HasColumnType("nvarchar(max)");
                b.HasKey("UserId");
                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
